apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline
  name: ml-pipeline
spec:
  selector:
    matchLabels:
      app: ml-pipeline
  template:
    metadata:
      labels:
        app: ml-pipeline
    spec:    
      volumes:
        - name: config-volume
          configMap:
            name: ml-pipeline-ui-configmap
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name: DBCONFIG_USER
          valueFrom:
            secretKeyRef:
              name: off-cluster-storage-secret
              key: rds_username
        - name: DBCONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: off-cluster-storage-secret
              key: rds_password
        - name: DBCONFIG_DBNAME
          valueFrom:
            secretKeyRef:
              name: off-cluster-storage-secret
              key: db_name_pipelines
        - name: DBCONFIG_HOST
          valueFrom:
            secretKeyRef:
              name: off-cluster-storage-secret
              key: rds_host
        - name: DBCONFIG_PORT
          valueFrom:
            secretKeyRef:
              name: off-cluster-storage-secret
              key: rds_port


        - name: OBJECTSTORECONFIG_PORT
          value: ""
        - name: OBJECTSTORECONFIG_SECURE
          value: "true"
        - name: OBJECTSTORECONFIG_BUCKETNAME
          valueFrom:
            secretKeyRef:
              name: off-cluster-storage-secret
              key: s3_bucket
        - name: OBJECTSTORECONFIG_REGION
          valueFrom:
            secretKeyRef:
              name:  off-cluster-storage-secret
              key: s3_region
        - name: OBJECTSTORECONFIG_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name:  off-cluster-storage-secret
              key: s3_access_key
        - name: OBJECTSTORECONFIG_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: off-cluster-storage-secret
              key: s3_secret_key

        image: gcr.io/ml-pipeline/api-server:dummy
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-api-server
        ports:
        - name: http
          containerPort: 8888
        - name: grpc
          containerPort: 8887
        readinessProbe:
          exec:
            command:
              - wget
              - -q # quiet
              - -S # show server response
              - -O
              - "-" # Redirect output to stdout
              - http://localhost:8888/apis/v1beta1/healthz
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
              - wget
              - -q # quiet
              - -S # show server response
              - -O
              - "-" # Redirect output to stdout
              - http://localhost:8888/apis/v1beta1/healthz
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
      serviceAccountName: ml-pipeline
